### PR TITLE
Bump porter + terraform version, template base image Debian versions, and template terraform and az cli versions

### LINKED ISSUE #4153: Template images are showing CVEs
Example shown below of base workspace image when scanned in Defender.

Appears primarily to be related to the following components:

- Porter
- Porter Mixins
- Az CLI
- Terraform

And to a lesser extent the base Debian image.

Image

### PR DESCRIPTION
**Pull request by jonnyry**
# Resolves #4153

## What is being addressed

Bumps versions of the following:

In the Dev Container:
- Porter from v1.0.5 => v.1.2.0
- Porter Az Plugin from v1.2.0 => v1.2.3
- Porter Terraform Mixin v1.0.2 => v1.0.5
- Porter Az Mixin v1.0.1 => v1.0.4
- Terraform from v1.4.5 => v1.9.8

In template images:
  - Base Debian Image from buster/bullseye => bookworm
  - Terraform from various => 1.9.8
  - Az cli from various => 2.67.0

## Note - Templates not updated

The following templates were not updated due to incompatibilities that arose while building:

- OHDSI
- MLFlow (since removed from build by another PR)

### CODE REVIEW

**Comment by tamirkamara** [comment]
@jonnyry will you also upgrade terraform in devcontainer / core? 
(maybe in a different PR)

**Comment by jonnyry** [comment]
> @jonnyry will you also upgrade terraform in devcontainer / core? (maybe in a different PR)

Hi @tamirkamara I've updated the core version in the Dev Container here:

https://github.com/microsoft/AzureTRE/pull/4158/commits/f7cda3a883fdc54bd21dbc4aa0a69c2e0eaaffff

Is there somewhere else in the core I'm missing?

**Comment by jonnyry** [comment]
Setting to draft while the following PRs get merged & we can update the mixin version numbers in this PR:

https://github.com/getporter/az-mixin/pull/72
https://github.com/getporter/terraform-mixin/pull/120

**Comment by tamirkamara** [comment]
Overall this looks good to me but I think we're waiting to see if we'll be able to use a production channel for the mixins, right?
So I will review once we know we want to merge it.

**Comment by jonnyry** [comment]
> Overall this looks good to me but I think we're waiting to see if we'll be able to use a production channel for the mixins, right? So I will review once we know we want to merge it.

Hi @tamirkamara the mixins are now released on the production channel.  Could you review?  Thanks.

**Review by marrobi — APPROVED** [review]
I've run a few manual tests, and all seems good. Great work, thanks for following this through upstream with the Porter team..

**Comment by marrobi** [comment]
/test-force-approve 
 
 as completed here - https://github.com/microsoft/AzureTRE/actions/runs/12259982943

**Pull request merged**
