### PR TITLE
Update to Release Docs

### PR DESCRIPTION
**Pull request by tim-allen-ck**
## What is being addressed

Current Release Documentation is not up-to-date.

## How is this addressed

- Documentation has been updated to address changes in the process

### CODE REVIEW

**Review by Danny-Cooke-CK — APPROVED** [review]
approved

**Comment by marrobi** [comment]
@tim-allen-ck not sure it addresses these points in the issue?

- [ ] Remove any Terraform or Database migrations that are from previous versions.
- [ ] Do an upgrade test from the last version, and not skipped any versions.
- [ ] Update terraform providers to latest versions

**Comment by tim-allen-ck** [comment]
> @tim-allen-ck not sure it addresses these points in the issue?
> 
> * [ ]  Remove any Terraform or Database migrations that are from previous versions.
> * [ ]  Do an upgrade test from the last version, and not skipped any versions.
> * [ ]  Update terraform providers to latest versions

Agreed, changed the description to reflect that

**Review by marrobi — APPROVED** [review]
LGTM

**Pull request merged**
