### PR TITLE
Multiple edits to address Typos/Grammar in text

### PR DESCRIPTION
**Pull request by clarotech**
Docs update.

### CODE REVIEW

**Comment by clarotech** [comment]
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by marrobi** [comment]
@clarotech thank you for the pull requests. We will review them in due course.

You will need to type a comment with:

```
@microsoft-github-policy-service agree
```

to accept the CLA.

**Comment by clarotech** [comment]
Thanks for the feedback.

@microsoft-github-policy-service agree

**Review by marrobi — APPROVED** [review]
Thanks.

**Pull request merged**
