### PR TITLE
Validate required secrets have value

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

Some secrets must exist and have values, but something people forget to define them. In this case the errors might not be easy to understand.
An example issue: https://github.com/microsoft/AzureTRE/issues/2984

## How is this addressed

- Add a step in the reusable deployment workflow that checks that required secrets exist with non-empty values.

### CODE REVIEW

**Review by guybartal — CHANGES_REQUESTED** [review]
required secret is missing in test: ```MS_TEAMS_WEBHOOK_URI```

**Comment by tamirkamara** [comment]
> required secret is missing in test: `MS_TEAMS_WEBHOOK_URI`

**Comment by tamirkamara** [comment]
> required secret is missing in test: `MS_TEAMS_WEBHOOK_URI`

It's not really missing since we sometimes remove the step that uses it (especially in the deployment repo)

**Review by guybartal — APPROVED** [review]

**Pull request merged**
