### PR TITLE
Enable Workspace owners to create Airlock requests and remove need for email

### LINKED ISSUE #3904: Enable Workspace owners to create Airlock requests and remove need for email
**Describe the bug**

When creating a new airlock request, the airlock seems to expect at least one member of the Workspace Researchers role with an email address assigned.

Besides the odd requirement for this (considering bug #3506), having only Workspace Owners should be supported too.

**Steps to reproduce**

1. Create a workspace with airlock enabled.
1. Assign Workspace Owner with an email address populated.
1. Try to create an Airlock request.

**Azure TRE release version (e.g. v0.14.0 or main):** v0.16.0

**Deployed Azure TRE components - click the (i) in the UI:**
- UI: 0.5.17
- API: 0.16.9

### PR DESCRIPTION
**Pull request by marrobi**
# Fixes #3904

This pull request introduces a new configuration variable, `ENABLE_AIRLOCK_EMAIL_CHECK`, which is set to `false` by default. When set to `true`, the system will require users to have an email address before creating an Airlock request. This change improves the default user experience and enables tests to be run by service prinicpals without an email address.

If the check is enable, Workspace Owners with addresses are now sufficient, not just resarchers.

### CODE REVIEW

**Review by anatbal — APPROVED** [review]
LGTM, please add a test for the notifier https://github.com/microsoft/AzureTRE/blob/1ffb09baf37f4599adfd65b4259fdda7564da408/api_app/event_grid/event_sender.py#L37

**Comment by marrobi** [comment]
> LGTM, please add a test for the notifier
> 
> https://github.com/microsoft/AzureTRE/blob/1ffb09baf37f4599adfd65b4259fdda7564da408/api_app/event_grid/event_sender.py#L37

Added, probably should be at a lower level - event_sender, but easier to add here, seems to pass ok.

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Pull request merged**
