### PR TITLE
Update role assignment check to handle service principals

### LINKED ISSUE #2461: E2E fail to retrieve workspace by id
**Describe the bug**

E2E are consistently fail after #2453 
The error gist is this and can be reproduced locally by using the test (automation) account to issue the GET request.

  File "/api/./api/routes/workspaces.py", line 69, in retrieve_workspace_by_workspace_id
    user_role_assignments = get_user_role_assignments(user)
  File "/api/./api/routes/resource_helpers.py", line 67, in get_user_role_assignments
    return access_service.get_user_role_assignments(user.id)
  File "/api/./services/aad_authentication.py", line 313, in get_user_role_assignments
    raise AuthConfigValidationError(f"{strings.ACCESS_UNABLE_TO_GET_ROLE_ASSIGNMENTS_FOR_USER} {user_id}")
services.access_service.AuthConfigValidationError: Unable to get role assignments for user ade81c51-edee-4f17-ac8d-1becb3dd7352

### PR DESCRIPTION
**Pull request by stuartleeks**
# Resolves #2461

## What is being addressed

Change user role assingment lookup to determine the identity type and look up role assignments for user or service principal depending on type

## How is this addressed

- Update to handle user and servicePrincipal
- Also update workspace list endpoint to gracefully fail if a workspace is missing auth info (Fixes `Auth configuration not available for workspace` error)

### CODE REVIEW

**Comment by stuartleeks** [comment]
/test 

re-run after SB delete ("resource exists error")

**Review by LizaShak — APPROVED** [review]
Looks good!

**Pull request merged**
