### PR TITLE
include min memory for dev container to avoid hang issues

### PR DESCRIPTION
**Pull request by lordlinus**
## What is being addressed
Using dev container with less than 8 GB is causing issues during deployment.

## How is this addressed

Update host requirements spec with min 8 GB

### CODE REVIEW

**Comment by tamirkamara** [comment]
@lordlinus Is this really not going to work with less than 8GB?
How did you came across to that kind of lowend machine?

**Comment by tamirkamara** [comment]
@lordlinus Asking again since I worked on codespaces with just 4GB memory. Are you sure about this?

**Comment by lordlinus** [comment]
@tamirkamara apologies for late reply, i did encounter both disk and memory issue when doing a full make `make all`

**Comment by tim-allen-ck** [comment]
@lordlinus are you still finding this is a problem?

**Comment by lordlinus** [comment]
Hi @tim-allen-ck i have set my default to 8 GB and no issues. If no one else has this issue you can leave it at the current default.
Thanks

**Pull request closed without merging**
