### PR TITLE
Adding Tenant choices

### LINKED ISSUE #2360: AD tenant options

### PR DESCRIPTION
**Pull request by ross-p-smith**
# Fixes #2360 

## What is being addressed

Add an extra page about the Tenant Choices for TRE and fix up the docs to make sure `make auth` is run at the beginning, before `make all`

### CODE REVIEW

**Comment by ross-p-smith** [comment]
/test-force-approve

(it's docs changes)

**Comment by marrobi** [comment]
@ross-p-smith In the dedicated TRE tenant image - it is labelled "Dev " should it just be TRE AD? Also is the bold text at the bottom relevant to the dedicated tenant image.

**Review by marrobi — APPROVED** [review]
@ross-p-smith In the dedicated TRE tenant image - it is labelled "Dev " should it just be TRE AD? Also is the bold text at the bottom relevant to the dedicated tenant image.

**Comment by marrobi** [comment]
Lets get this merged, @ross-p-smith I would have updated the images, but don't have the source files.  See issue #2399

**Pull request merged**
