### PR TITLE
Disable base workspace upgrade

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

This [issue](https://github.com/microsoft/AzureTRE/issues/2913) prevents a normal upgrade flow for the base workspace so we need to disable it for the time being.

### CODE REVIEW

**Review by LizaShak — APPROVED** [review]

**Comment by marrobi** [comment]
@tamirkamara @LizaShak this will break Guacamole as it relies on the upgrade step to add redirect URIs.

How hard is it to fix the Redaction issue?

**Comment by tamirkamara** [comment]
It's hard and @damoodamoo is fixing it.
In the meantime, I'll bring back the step calling the script directly.

**Comment by tamirkamara** [comment]
I now see you deleted the update redirect urls script in that workspace upgrade PR which I don't get (and I approved it). Anyway, I'll work on reverting it.

**Pull request merged**
