### PR TITLE
Pin cryptography python package for TRE CLI

### LINKED ISSUE #3579: Error on opening repo in a codespace or locally in devcontainer
The error happens on building devcontainer, related to run `make  install-cli `
Please note, that we did not make any updates to repo, just started with a new docker installation and previously was running fine

`#28 8.066   self.initialize_options()
microsoft/AzureTRE#28 8.069 error: cryptography 41.0.1 is installed but cryptography<41,>=0.6 is required by {'msal'}
microsoft/AzureTRE#28 8.099 	
2023-06-02 11:44:19.259Z: microsoft/AzureTRE#28 ERROR: executor failed running [/bin/bash -o pipefail -c make install-cli && echo -e "\n# Set up tre completion\nsource <(_TRE_COMPLETE=bash_source tre)" >> ~/.bashrc]: exit code: 2`

I have also attached the full log:

[creation.log](https://github.com/microsoft/AzureTRE/files/11635306/creation.log)

Steps to reproduce:

1. Clone repo https://github.com/microsoft/AzureTRE-Deployment in 
2. open in visual studio code
3. Reopen in container - fails
Or:
2. Open in codespace - the same error.

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #3579

TRE CLI will not install in deployment repo.

## What is being addressed
- Pinned cryptography<41

### CODE REVIEW

**Comment by marrobi** [comment]
For reference azure-cli-core requires msal 1.20.0 - which does not support the latest cryptography packages.

> msal 1.22.0 is installed but msal[broker]==1.20.0 is required by {'azure-cli-core'}

azure-cli-core dev branch now supports msal 1.22.0 - updated 2 weeks ago - https://github.com/Azure/azure-cli/commit/2e585451ad80518bc85a0aa3ab4bb8f203313e04 (since creation of the PR), but not yet released. When this is released we can remove this pin.

cc @tamirkamara @martinpeck

**Comment by tamirkamara** [comment]
@marrobi 1.22.0 is here and already opened by the bot last month: https://github.com/microsoft/AzureTRE/pull/3464
IIRC, I tried checking it and there's some impact on/from other dependencies too so it's not a quick merge. But I might be mistaken...

**Comment by marrobi** [comment]
> @marrobi 1.22.0 is here and already opened by the bot last month: #3464 IIRC, I tried checking it and there's some impact on/from other dependencies too so it's not a quick merge. But I might be mistaken...

But `azure-cli-core` does not support 1.22.0, only 1.20.0, so we can't update msal to 1.22.0 until a new `azure-cli-core` release is created that will will support it. 

This pinning is only in the TRE cli.

**Comment by marrobi** [comment]
Closed in favour of #3601

**Pull request closed without merging**
