### PR TITLE
Resource Processor: Configure logging handler per process

### PR DESCRIPTION
**Pull request by tanya-borisova**
# PR for issue https://github.com/microsoft/AzureTRE/issues/1688

## What is being addressed

Currently, logs from child processes of Resource Procesor runner aren't appearing in LogAnalytics. This PR fixes that 

## How is this addressed

- Refactor logging initialisation into a separate method
- Call method in each thread so that each process is configured with the`AzureLogHandler` handler separately 
- Pass logger_adapter into methods instead of having a method-level variable
- Only configure console logger in the parent thread

Screenshots:
image

image

### CODE REVIEW

**Review by martinpeck — APPROVED** [review]
Nice! LGTM!

**Review by ross-p-smith — APPROVED** [review]

**Pull request merged**
