### PR TITLE
Fix Firewall Logging

### PR DESCRIPTION
**Pull request by martinpeck**
# PR for issue #1745 

This switches logging for the firewall back to the generic log tables, rather than dedicated tables, as the dedicated table logging doesn't appear to work!

To test this I needed to...

- delete the firewall service from CosmosDB
- run `make firewall-install`

Once done, I was then able to...

- visit the jumpbox
- use Edge to try and access random website (e.g. `cheese.com`)
- wait a bit, and then see the logs in the Log Analytics workspace

e.g. the following query returned logs...

```
AzureDiagnostics | where
msg_s contains "cheese.com"
```

### CODE REVIEW

**Comment by martinpeck** [comment]
Tests passed, but linting picked up an issue in the `firewall.tf`.
Have fixed, and pushed update

**Review by marrobi — APPROVED** [review]
LGTM

**Pull request merged**
