### PR TITLE
Open AI Workspace Service

### PR DESCRIPTION
**Pull request by harryy94**
Addition of Open AI Workspace Service for #3810 

This builds upon @marrobi 's  original draft PR.

We are able to install an Open AI service and access it via the VM, and are still in progress of doing more tests, but welcome any feedback in the meantime!

### CODE REVIEW

**Comment by marrobi** [comment]
Works great for me, once I sorted quota issues out. I had to manually set the version, as the default "auto update" selection didn;t work, seemed to be trying to use a version not available in the region.

image

Blocked external:

image

Works internal:
image

We should surface the API key somehow as a later issue as per #2401 

Thanks!

**Comment by marrobi** [comment]
@harryy94 can you add the tags, not sure what was wrong before, but should support them:
image

**Comment by harryy94** [comment]
> @harryy94 can you add the tags, not sure what was wrong before, but should support them: image

Hi, thanks for your review :) For the above I realised I forgot this line

```
tags                          = local.workspace_service_tags
```

so I've added that in on the OpenAI instance. The other error I was getting was I accidentally tried to add tags on the deployment instead of the instance which doesn't support tags.

**Comment by marrobi** [comment]
/test-extended 3669487

Given base workspace and core changes doing full test.

**Comment by tim-allen-ck** [comment]
I seem to keep hitting this error: 
```bash
 Error: Failed to download module
│ 
│ Could not download module "terraform_azurerm_environment_configuration" (main.tf:30) source code from
│ "git::https://github.com/microsoft/terraform-azurerm-environment-configuration.git?ref=0.6.0": error downloading
│ 'https://github.com/microsoft/terraform-azurerm-environment-configuration.git?ref=0.6.0': /usr/local/bin/git exited with 128: fatal: detected
│ dubious ownership in repository at
│ '/workspaces/AzureTRE/templates/workspace_services/openai/terraform/.terraform/modules/terraform_azurerm_environment_configuration'
│ To add an exception for this directory, call:
│ 
│       git config --global --add safe.directory
│ /workspaces/AzureTRE/templates/workspace_services/openai/terraform/.terraform/modules/terraform_azurerm_environment_configuration
│ 
```
Any ideas to add it permanently in?

**Comment by marrobi** [comment]
> ```shell
> detected
> │ dubious ownership in repository at
> ```

This in the dev container when building? I didn't get that. Weird.

That module is used by other bundles too, so weird just seeing it now.

**Comment by tim-allen-ck** [comment]
> > ```shell
> > detected
> > │ dubious ownership in repository at
> > ```
> 
> This in the dev container when building? I didn't get that. Weird.
> 
> That module is used by other bundles too, so weird just seeing it now.

Yeah I figured it was used elsewhere. 
Yes, doing a container deploy I ended up doing it multiple times for different bundles in the end.

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Pull request merged**
