### PR TITLE
Update gitea workspace

### LINKED ISSUE #2801: Gitea Workspace Service documentation
**Describe the bug**
The documentation for setting up Gitea as a Workspace Service is not very detailed and is out of date. 

I am trying to set up Gitea but there are steps within the docs that no longer apply. Such as: 

"The Gitea workspace service container image needs building and pushing:
`make build-gitea-workspace-service-image push-gitea-workspace-service-image`"

There is also not enough information or it is incorrect as following the steps gives a 403 error when trying to connect to the service.

**Steps to reproduce**

1. Run `make bundle-build bundle-publish DIR=templates/workspace_services/gitea`
1. Run `make bundle-register DIR=templates/workspace_services/gitea/ BUNDLE_TYPE=workspace_service`
1. Go to the TRE UI and Deploy Gitea
2. When Deploying fill in the required information:
2.1 Enter the OpenID Client ID is the Workspace App registration Application (client) ID. _This can be found in the KeyVault for the Workspace and on the Overview page of the App registration_
2.2 Enter the OpenID Client Secret. _This can only be found in the KeyVault for the Workspace._
2.3 Enter the OpenID Authority: https://login.microsoftonline.com/{tenant_id}/v2.0
3. Within the App registration, go to the Authentication tab in the blade on the left-hand side and add the Gitea redirect URI. In the form `https://<gitea_url>/user/oauth2/oidc/callback` (gitea_url can be found by clicking on the details tab of the deployed service)
4. Deploy the Workspace Service
**This is where it fails**
5. Press Connect on the Workspace Service. 
6. I see a 403 error 

Screenshot 2022-10-31 at 16 01 40

In the documentation it says `Navigate to the Gitea workspace service and from the menu click the Sign in button.` Does this mean press Connect and it should ask you to sign in?

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #2801

## What is being addressed

Update Gitea workspace to use latest TRE features.

## How is this addressed

- Read AD details from keyvault
- Use pipeline for firewall updates
- Update documentation
- Upgrade to latest Gitea version
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by marrobi** [comment]
/test-force-approve - not included in e2e tests.

**Review by damoodamoo — APPROVED** [review]
looks good to me!

**Comment by guybartal** [comment]
Hi @marrobi,
 
Following up our teams chat,
TFLINT scans all lines in the file you've changed, even lines that you didn't touch,
in this case two resources were found without prior tags which are "azurerm_user_assigned_identity" and "azurerm_key_vault_secret".

**Pull request merged**
