### PR TITLE
Network module in base workspace

### LINKED ISSUE #1526: Storage share fails to delete from base workspace
**Describe the bug**
When trying to delete a (base) workspace instance, the action might fail due to a problem removing the storage share:

shares.Client#Delete: Failure sending request: StatusCode=0 -- Original Error: Delete "https://stgws84a2.file.core.windows.net/vm-shared-storage?restype=share": EOF

> True deleting_failed aad1d169-e124-43ed-859a-07b0cdbb84a2: Error context message = ╷ │ Error: deleting File Share "vm-shared-storage" (Storage Account "stgws84a2" / Resource Group "rg-***-ws-84a2"): shares.Client#Delete: Failure sending request: StatusCode=0 -- Original Error: Delete "https://stgws84a2.file.core.windows.net/vm-shared-storage?restype=share": EOF │  │  ╵ Error: error running command /cnab/app/terraform terraform destroy -auto-approve -input=false -var address_space=10.0.68.0/24 -var location=*** -var shared_storage_quota=50 -var tre_id=*** -var tre_resource_id=aad1d169-e124-43ed-859a-07b0cdbb84a2: exit status 1 Error: mixin execution failed: exit status 1 Error: 1 error occurred: 	* container exit code: 1, message: <nil>   az login --identity -u 4c1a5d14-72a0-433f-b96b-4d96d3a6e6df && az acr login --name *** && porter uninstall "aad1d169-e124-43ed-859a-07b0cdbb84a2"  --reference ***.azurecr.io/tre-workspace-base:v0.1.10  --param address_space="10.0.68.0/24" --param arm_use_msi="true" --param azure_location="***" --param id="aad1d169-e124-43ed-859a-07b0cdbb84a2" --param tfstate_container_name="tfstate" --param tfstate_resource_group_name="***mgmt" --param tfstate_storage_account_name="***state" --param tre_id="***" --cred ./vmss_porter/azure.json --allow-docker-host-access --force && porter show aad1d169-e124-43ed-859a-07b0cdbb84a2

**Steps to reproduce**

1. More likely to happen after we merge to main, but not every time

### PR DESCRIPTION
**Pull request by tamirkamara**
Fixes #1526 

## What is being addressed

Storage share fails to be deleted when the resource processor uninstall a workspace.

## How is this addressed

- Package all networking resources in the base workspace as a module to be able to easily depend on all of it
- Private endpoints depend on the module
- Increase service bus max message size for the deployment status to cope with larger messages usually returned on errors

### CODE REVIEW

**Comment by marrobi** [comment]
How will this sort the delete storage issue? Is there a depend the networking? Either way think its a good thing to do.

**Review by marrobi — APPROVED** [review]
Haven't tested, and on mobile so not gone through in detail line by line, but in principle, all good.

**Review by eladiw — APPROVED** [review]

**Comment by tamirkamara** [comment]
> How will this sort the delete storage issue? Is there a depend the networking? Either way think its a good thing to do.

@marrobi, now all private endpoints depend on the network, meaning that on destroy first the storage share is deleted, then its private endpoint and network last.

**Pull request merged**
