### PR TITLE
Add storage account check to avoid name clash

### PR DESCRIPTION
**Pull request by marrobi**
Temporary fix for #2893 

This pull request adds a storage account check to the create_workspace_item method in the WorkspaceRepository. The check ensures that a storage account with the last four digits of the workspace ID is available before creating a new workspace item.

### CODE REVIEW

**Review by marrobi — COMMENTED** [review]
/test

**Comment by tim-allen-ck** [comment]
@marrobi ddi you want to put this into the next release? Shall I pick this up?

**Comment by marrobi** [comment]
Yes please, if you can test etc. We need to look at the wider issue in the near future.

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Review by Danny-Cooke-CK — APPROVED** [review]
approved

**Pull request merged**
