### PR TITLE
Fix UI Failing to get workspaces for non workspace admin users

### LINKED ISSUE #3489: Workspace Owners and Researchers recieve browser Error and cannot see workspaces
When a user is assigned workspace Researcher or owner along with being a member of TRE Users the recieve the error below:

(when the user is assigned TRE Admin the error disappears)

Uh oh!
This area encountered an error that we can't recover from. Please check your configuration and refresh.
Further debugging details can be found in the browser console.

The Browser console has this output:
peError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128)
ps @ react-dom.production.min.js:189
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
GenericErrorBoundary.tsx:21 UNHANDLED EXCEPTION TypeError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128) {componentStack: '\n    at WC (https://imperialtre.uksouth.cloudapp.a…pp.azure.com/static/js/main.aba16646.js:2:691445)'}
value @ GenericErrorBoundary.tsx:21
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128)
ps @ react-dom.production.min.js:189
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
GenericErrorBoundary.tsx:21 UNHANDLED EXCEPTION TypeError: Cannot read properties of undefined (reading 'length')
    at WC (ResourceContextMenu.tsx:202:24)
    at Sa (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at gc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128) {componentStack: '\n    at WC (https://imperialtre.uksouth.cloudapp.a…pp.azure.com/static/js/main.aba16646.js:2:691445)'}
value @ GenericErrorBoundary.tsx:21
i.componentDidCatch.r.callback @ react-dom.production.min.js:190
Bi @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Cc @ react-dom.production.min.js:281
oc @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14

### PR DESCRIPTION
**Pull request by yuvalyaron**
# Fixes #3489 

- Added missing enrichment in the the API
- Although it shouldn't happen now, added validation in the UI to ensure that `nonMajorUpgrades` is not null

### CODE REVIEW

**Review by martinpeck — APPROVED** [review]
LGTM! Thanks for fixing this @yuvalyaron!

**Comment by yuvalyaron** [comment]
successful test run:
https://github.com/microsoft/AzureTRE/actions/runs/5004406367

**Pull request merged**
