### PR TITLE
Add temporary workaround for when id with last 4 chars exists

### LINKED ISSUE #2893: Workspace deploy fails because storage account is not unique
**Describe the bug**

I've just deployed a workspace and get

```
mError: \u001b[0m\u001b[0m\u001b[1mcreating Azure Storage Account \"stgws2a73\": storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"StorageAccountAlreadyTaken\" Message=\"The storage account named stgws2a73 is already taken.
```

looks like the last 4 chars are maybe not unique enough. Seems odd though if it's ~1/10^6 chance

**Steps to reproduce**

1. Deploy a workspace
2. Be unlucky!

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #2893

- Add function that checks for existance of worksapce_id with the same last 4 digits.
- When generating worksapce_id while loop until none returned.

Overhead is limited, but improves experience until we have a full fix.

### CODE REVIEW

**Review by SvenAelterman — APPROVED** [review]
LGTM

**Comment by marrobi** [comment]
/test-force-approve

Passed - https://github.com/microsoft/AzureTRE/actions/runs/6109096538

**Pull request merged**
