### PR TITLE
Airlock function private endpoint for internal storage

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

The Airlock Function uses a storage account internally but does it over public network.
This is part of #2518 

## How is this addressed

- Add Private Endpoint(s) for the storage account
- Block public internet access to the storage account

### CODE REVIEW

**Review by guybartal — APPROVED** [review]
LGTM

**Comment by yuvalyaron** [comment]
@tamirkamara 
why does the airlock function need a private endpoint?
isn't a firewall rule in the storage account enough?

**Comment by tamirkamara** [comment]
> @tamirkamara why does the airlock function need a private endpoint? isn't a firewall rule in the storage account enough?

@yuvalyaron I imagine you'd define a rule with the subnet/vnet internal address, right? A private endpoint is essencially a way to give the storage account an ip address in the vnet and by such we make sure all communication is done over private network. IIRC, you need this anyway for the firewall rule mentioned above.

**Pull request merged**
