### PR TITLE
Upgrade azurerm terraform provider from v3.112.0 to v3.117.0

### LINKED ISSUE #4004: Core deployment errors - Error: reading blob properties for Storage Account
Deploying a fresh TRE from 2 commits behind main (1ffb09baf37f4599adfd65b4259fdda7564da408)...

Experienced storage account failures on two seperate deployments:

Capture

Capture3

### PR DESCRIPTION
**Pull request by jonnyry**
# Resolves #4004

## What is being addressed

Upgrade azurerm terrafom provider from v3.112.0 to v3.117.0.

An intermittent issue exists where deploying a TRE using the same name as a recently deleted TRE causes the deployment to fail due to DNS issues with storage accounts (see #4004).  This has been resolved in azurerm terraform provider [v3.113.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.113.0)

### CODE REVIEW

**Review by tim-p-allen — APPROVED** [review]
LGTM

**Review by tamirkamara — APPROVED** [review]

**Comment by jonnyry** [comment]
/test-force-approve
Extended test failure appears unrelated to this change as occurring in other PRs (without this change)

**Pull request merged**
