### PR TITLE
Register TRE bundle workflow

### PR DESCRIPTION
**Pull request by guybartal**
## What is being addressed

This workflow allows TRE Admins to publish and register a specific TRE bundle.

### main changes

1. Adding a new Register TRE Bundle workflow with the following inputs:
- Bundle type (workspace, workspace-service, shared-service or user resource
- Bundle name
- Workspace service to register a user resource inside (required only if bundle-type == user-resource)
2. Support for multiple command lines inside devcontainer action for readability and maintainability.

### CODE REVIEW

**Comment by marrobi** [comment]
@guybartal would this be better in the `AzureTRE-Deployment` repository?

**Comment by tim-allen-ck** [comment]
I think it should probably run a `register` before it runs a publish too

**Comment by tim-allen-ck** [comment]
> @guybartal would this be better in the `AzureTRE-Deployment` repository?

agree with @marrobi

**Comment by marrobi** [comment]
> > > @guybartal would this be better in the `AzureTRE-Deployment` repository?
> > 
> > 
> > agree with @marrobi
> 
> @tamirkamara WDYT?

So my reasoning for having it in the deployment repo is:
1. It's unlikely to be run in this repo.
2. Avoids making PRs in this repo, and then having to wait for a release to update the other repo, when an just do it direct in the deployment repo.

**Pull request closed without merging**
