### PR TITLE
Enable CMK encryption for storage queues and tables

### PR DESCRIPTION
**Pull request by yuvalyaron**
# Part of #4142

## What is being addressed

Added CMK support for all storage types such as tables and queues in the storage account, the default is blobs and files only.

**NOTE:** This PR covers core and management only, the templates will be covered in another PR.

### CODE REVIEW

**Comment by yuvalyaron** [comment]
waiting for https://github.com/microsoft/AzureTRE/pull/4178

**Review by LizaShak — APPROVED** [review]
LGTM

**Review by tamirkamara — APPROVED** [review]

**Pull request merged**
