### PR TITLE
Prevent terraform creating Azure ML on upgrade

### LINKED ISSUE #3183: AML Workspace Deleted on Upgrade
If carry out an upgrade on an Azure ML workspace it gets deleted. 

This is due to terraform destroying the resource...

```      - image_build_compute_name                     = "cp-83ab" -> null # forces replacement```

### PR DESCRIPTION
**Pull request by marrobi**
Resolves #3183
## What is being addressed
Two properties are being updated as part of terraform plan, `image_build_compute_name` causes the resource to be destroyed. 

Added them to `ignore_changes`.

### CODE REVIEW

**Comment by marrobi** [comment]
/test-force-approve

https://github.com/microsoft/AzureTRE/actions/runs/4073720658

**Review by tamirkamara — APPROVED** [review]

**Pull request merged**
