### PR TITLE
Handle non-success error codes in healthcheck

### LINKED ISSUE #1593: API healthcheck error: `parse error: Invalid numeric literal`
Error in the API Healthcheck stage in PR build:

```
parse error: Invalid numeric literal at line 1, column 7
make: *** [Makefile:326: api-healthcheck] Error 4
Error: Process completed with exit code 2.
```

Seen here: https://github.com/microsoft/AzureTRE/runs/5676435723?check_suite_focus=true#step:4:155

### PR DESCRIPTION
**Pull request by stuartleeks**
# PR fixes #1593

## What is being addressed

When the App Gateway returns a `502 Bad Gateway` response, the body is HTML rather than JSON and we get an error: `parse error: Invalid numeric literal at line 1, column 7`

## How is this addressed

This PR changes the healthcheck to only attempt to parse response as JSON for 200 success responses. This avoids attempting to parse HTML from 502 Bad Gateway responses as JSON.

### CODE REVIEW

**Comment by stuartleeks** [comment]
/test

Previous run got the `502 Bad Gateway` which confirmed the PR fixes the error output!
Re-running in the hope that the Bad Gateway is resolved to test the success path

**Comment by stuartleeks** [comment]
/test

Previous run got Gateway timeout on registering bundles

**Review by damoodamoo — APPROVED** [review]

**Review by martinpeck — APPROVED** [review]

**Pull request merged**
