### PR TITLE
Update obsolete TF properties

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

Some of the properties name have been replaced in the Terraform configuration files.

## How is this addressed

- Use up-to-date property names

### CODE REVIEW

**Review by marrobi — APPROVED** [review]
LGTM, don't forget the changelog! Thanks.

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Comment by marrobi** [comment]
@tamirkamara you didn't update the changelog!

**Comment by tamirkamara** [comment]
I know @marrobi. I opened the PR, started the test, went to sleep and this morning saw it's merged. You and @tim-allen-ck were quick.
I will open a small one to add a changelog the this.

**Pull request merged**
