### PR TITLE
azurerm_app_service_plan is deprecated and we should use azurerm_service_plan

### LINKED ISSUE #1815: Upgrade azurerm_app_service_plan
## Description

As a TRE Administrator
I want to use the latest Terraform App Service Plan
So that I don't use a deprecated Terraform Module

## Acceptance criteria

- [ ] No longer reference azurerm_app_service_plan

You can use the workspace app service plan as an example for the settings (azurerm_service_plan)

### PR DESCRIPTION
**Pull request by ross-p-smith**
Fixes #1815 

## What is being addressed

azurerm_app_service_plan is deprecated and we should use azurerm_service_plan

## How is this addressed

- This updates the core resource
- We will upgrade each workspace service in separate PR, so as we can test them individually and add e2e test
- Each resource needs to be AzureRM 3.5

### CODE REVIEW

**Review by eladiw — APPROVED** [review]
lgtm. what happens if there are no resources to migrate? will the migrate script skip?

**Comment by ross-p-smith** [comment]
> lgtm. what happens if there are no resources to migrate? will the migrate script skip?

Ideally, if there are no resources to migrate, it will just skip. However that's where the bug is at the moment (if there is NO state file, it breaks) :-(

**Pull request merged**
