### PR TITLE
Guacamole updates firewall with deployment pipeline

### LINKED ISSUE #2206: Guacamole configures firewall with deployment pipeline
## Description

As a TRE Developer
I want to configure required firewall rules with the deployment pipeline
So that firewall rules will be managed centrally in the shared service

## Acceptance criteria

- [ ] get_firewall_priorities.sh is removed
- [ ] Required rules are present in firewall on azure and in state of the firewall shared service
- [ ] Both install and uninstall work

### PR DESCRIPTION
**Pull request by tamirkamara**
# Resolves #2206 

## What is being addressed

Guacamole workspace service configured its firewall rules by using a script which is now obsolete as we have a deployment pipeline that should be used.

## How is this addressed

- Update the firewall shared service to support firewall network rules
- Update the Guacamole workspace service with a step to add a firewall rule
- Remove redundant bundle dockerfile.tmpl files as the standard one is enough
- Upgrade Terraform CLI version and AzureRM versions
- Firewall Terraform update around diagnostics to prevent repeat changes
- Various Terraform changes to keep the linter happy
- Update both bundle versions to 0.4.0 as this is not a minor change

### CODE REVIEW

**Review by damoodamoo — APPROVED** [review]
LGTM!

**Comment by marrobi** [comment]
@tamirkamara given the firewall is a shared service, how do I get these changes into an existing TRE deployment? Thanks.

**Comment by tamirkamara** [comment]
> @tamirkamara given the firewall is a shared service, how do I get these changes into an existing TRE deployment? Thanks.

@marrobi unfortunately this is a manual process. I added a note in the changelog.

**Pull request merged**
