### PR TITLE
Airlock manager can create user resources

### LINKED ISSUE #2499: Airlock Manager can create user resources
## Description

As an Airlock Manager
I want to have a permission to create VMs in workspaces I'm added as an Airlock Manager
So that I can create a VM and use it review an Airlock request

## Acceptance criteria

- [ ] Airlock Manager can create user resources

### PR DESCRIPTION
**Pull request by JaimieWi**
# Resolves #2499 

## What is being addressed

Adding Airlock Manager role to allow creation of a user resource

## How is this addressed

- Add get_current_workspace_owner_or_researcher_user_or_airlock_manager to Workspaces.py Router and Create user resource method.
- For VM templates intended to be used by researchers (windowsvm and linuxvm), add authorizedRoles clause to include WorkspaceOwner and WorkspaceResearcher (so that Airlock Managers can't use them)

### CODE REVIEW

**Comment by martinpeck** [comment]
Thanks, @JaimieWi, for this PR.

As we've discussed elsewhere, and based upon feedback, we're going to go in a slightly different direction.
I'm going to close this PR without merging.

**Comment by tanya-borisova** [comment]
The PR has been reopened: as https://github.com/microsoft/AzureTRE/pull/2623 is now in main, we can make use of authorizedRoles field in resource template and restrict template intended to be used by Researchers

**Comment by tanya-borisova** [comment]
Closing this as the work is complete in https://github.com/microsoft/AzureTRE/pull/2649

**Pull request closed without merging**
