### PR TITLE
Fix health endpoint output

### LINKED ISSUE #1673: API health endpoint and solution monitoring
## Description

As a TRE Administrator, I want to know the status of my TRE solution so that I can address potential issues with its components.
As an App Gateway, I want to know if the API is healthy so that I can forward it requests.

The current use of the API health endpoint to do both is causing issues and we need to figure out what requirements are important for us and how to address them.

## Acceptance criteria

TBD

### PR DESCRIPTION
**Pull request by anatbal**
# Resolves #1673 

## What is being addressed

After re-enabling the health check again, there are two things which I missed that this PR fixes:
1.  Change the health endpoint output to return the real status (but still always returns 200)
2.  Enable the unit tests again

### CODE REVIEW

**Comment by stuartleeks** [comment]
When reading the PR description, I initially thought that this was changing the health endpoint status code. Looking at the code, it looks like this is still always returning a 200 response for the health endpoint regardless of the health of Cosmos etc - is that the case? (I think always returning 200 is a good thing, to be clear 😄 )

**Comment by anatbal** [comment]
> When reading the PR description, I initially thought that this was changing the health endpoint status code. Looking at the code, it looks like this is still always returning a 200 response for the health endpoint regardless of the health of Cosmos etc - is that the case? (I think always returning 200 is a good thing, to be clear 😄 )

You got it right, this intentionally still returns 200, just the json output has changed to reflect the true health status - meaning one can come and debug the system (but the api is still accessible, wont be shut down by Application Gateway)

**Review by stuartleeks — APPROVED** [review]
LGTM

**Pull request merged**
