### PR TITLE
v0.5.0 prep

### PR DESCRIPTION
**Pull request by stuartleeks**
Pre for v0.5.0 release:

- Update CHANGELOG ready for release
- Add component versions

**MARKING AS DRAFT**
This PR is marked as draft based on feedback from @marrobi around upgrade steps
There are also some questions around the firewall update and potential impact

### CODE REVIEW

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by stuartleeks** [comment]
/test-force-approve

CHANGELOG only changes

**Review by tanya-borisova — APPROVED** [review]

**Review by tanya-borisova — APPROVED** [review]

**Pull request merged**
