### PR TITLE
Remove innereye workspace & devtestlabs workspace service templates

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

We no longer need to have templates for an innereye workspace and devtestlabs workspace service, hence deleting those.

### CODE REVIEW

**Review by marrobi — APPROVED** [review]
Thanks. Worth noting if anybody is looking for th eInnerEye workspace that it is still available as a workspace service.

**Review by ross-p-smith — APPROVED** [review]

**Comment by tamirkamara** [comment]
/test-force-approve
Regular deployment tests can't run for this as the workflows have changed. 
Run with a branch workflow: https://github.com/microsoft/AzureTRE/actions/runs/2628615998

**Pull request merged**
