### PR TITLE
Fix: update `/test` builds to ensure PR code is tested

### PR DESCRIPTION
**Pull request by stuartleeks**
Remove the `checkout` step in devcontainer_run_command action as the parent jobs already include `checkout` steps (and target the ref for the PR)

### CODE REVIEW

**Comment by stuartleeks** [comment]
This line shows the PR code being exercised: https://github.com/microsoft/AzureTRE/runs/5466574832?check_suite_focus=true#step:7:120

This line from the previous run (which still had the duplicated checkouts) didn't output the test output: https://github.com/microsoft/AzureTRE/runs/5466411136?check_suite_focus=true#step:7:589

**Review by damoodamoo — APPROVED** [review]

**Comment by stuartleeks** [comment]
(force-approve to avoid re-testing after reverting the test code)

**Pull request merged**
