### PR TITLE
Assign VM Contributor role on workspace rg (not subscription)

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

We give the API identity this role on the subscription level which is too wide on the permission level and the scope level. 
This is a partial solution to #2389.

## How is this addressed

- Remove the role assignment from the subscription level and assign only to the workspace's resource group.

## Migration Steps (breaking change)

You will loose the ability to stop/start VMs in existing workspaces versioned 0.3.20 or lower. To address this, assign `Virtual Machine Contributor` to `id-api-<TRE_ID>` identity on pre-existing workspace resource groups.

### CODE REVIEW

**Review by LizaShak — APPROVED** [review]

**Comment by marrobi** [comment]
@tamirkamara this causes a larger issue for existing workspaces. Once the subscription level role assignment is removed users cannot list VM user resources as they rely on this role assignment to query the power state. This means as soon as try to list any resources get 500 errors.

Can we make sure this is covered in breaking changes, and maybe we need a script that adds the role to workspaces, or a way to update workspaces...

**Pull request merged**
