### PR TITLE
Fix nexus KeyVault secret creation 

### PR DESCRIPTION
**Pull request by dvoet**
# Fix nexus KeyVault secret creation

## What is being addressed

Nexus fails to create secret in KeyVault. Missing space added.

### CODE REVIEW

**Comment by marrobi** [comment]
@dvoet thanks, I'm guessing you are David, and this is a fix for the nexus account setup issue meninges on a call this week?! Apologies if I'm guessing incorrectly. 

Can you edit the PR description to explain please, and I'll test and merge.

**Comment by dvoet** [comment]
No, this is Doug Voet from The Broad Institute. We met last week. I ran into this problem in the script setting up nexus for the first time.

**Comment by marrobi** [comment]
Sorry, and thanks! I'll take a look at it tomorrow. Expect its the same issue someone else hit.

**Comment by dvoet** [comment]
it's a trivial thing, a missing space between a value and the next parameter name in a command line call

**Review by marrobi — APPROVED** [review]
Thanks.

**Pull request merged**
