### PR TITLE
Fix registration of templates with  no required or authorizedRoles defined.

### PR DESCRIPTION
**Pull request by nasaldrops**
Work to resolve this open issue: https://github.com/microsoft/AzureTRE/issues/3774

.get('required',[]) as suggested by marrobi.

### CODE REVIEW

**Comment by marrobi** [comment]
@nasaldrops thanks for the PR, could you add a test here -https://github.com/microsoft/AzureTRE/blob/e8da262b9d6e62babf5d27a693e98d642fa50832/api_app/tests_ma/test_db/test_repositories/test_resource_templates_repository.py#L22 

With a spec with the fields missing to ensure the code works?

Thank you.

**Comment by nasaldrops** [comment]
@microsoft-github-policy-service agree

**Comment by marrobi** [comment]
@nasaldrops if you can fix the issues raised in the checks, add a line to the changelog, that would be appreciated.

**Comment by marrobi** [comment]
@nasaldrops need to up the API version as per the build error...

**Comment by nasaldrops** [comment]
> @nasaldrops need to up the API version as per the build error...

Sorry about that - missed it

**Comment by marrobi** [comment]
Couple of imports seem to be wrong.

**Comment by marrobi** [comment]
/test-force-approve

Passed: https://github.com/microsoft/AzureTRE/actions/runs/7977819481

**Comment by marrobi** [comment]
Tests passed here - https://github.com/microsoft/AzureTRE/actions/runs/7986142720/job/21805940849 but for some reason check isn't going green.

**Review by marrobi — APPROVED** [review]
LGTM. Thanks for your patience.

**Pull request merged**
