### PR TITLE
Airlock UI: create review VM

### LINKED ISSUE #2738: UI for Airlock Review VM
https://www.figma.com/file/Ncl8TJsFf2WKf3frrqTbtq/AzureTRE-OSS-UI?node-id=1293%3A27999

### LINKED ISSUE #2766: Airlock UI - clicking between quick filters doesn't clear previous filters
When clicking between quick filters (i.e. my requests and awaiting my review), previous filters are not unset meaning that the status=in_review filter selected by "Awaiting my review" will remain when clicking My Requests, even though it should show requests of all states

### PR DESCRIPTION
**Pull request by jjgriff93**
Continuation of PR #2759 which has test environment conflicts

Resolves #2738
Resolves #2766 

## What is being addressed

Adds ability to deploy a review Vm in airlock review UI and open to view airlock request data securely in the review workspace

## How is this addressed

- Redesigned review experience as multi-step modal
- Implemented create-review-vm endpoint
- Display relevant resource state (created, not created, creating) 
- Added workspace scope option to componentManager hook so we can check for updates on resource that's in a different workspace to the current context (needed for import review Vms that reside in a different workspace)
- Changed create-review-vm api endpoint to return airlock request as well as create vm operation to reduce calls and latency on front-end and potential state mismatch

image

image

image

Note: this only supports single review VMs currently. A follow-up story adds support for multiple reviewers' Vm resources: #2764

Also includes a small fix for filter switching #2766 and a fix for Nexus tf arguments error

### CODE REVIEW

**Review by tanya-borisova — APPROVED** [review]

**Comment by jjgriff93** [comment]
Forcing test approval as previous test succeeded (https://github.com/microsoft/AzureTRE/actions/runs/3296838499) before merging minor change from main

**Pull request merged**
