### PR TITLE
Fix  .github/workflows/lets_encrypt.yml

### LINKED ISSUE #3978: Renew Lets Encrypt Certificates GitHub Action is broken
The **Renew Lets Encrypt Certificates** GitHub Action is broken...

### 1. Fails with AZURE_ENVIRONMENT: unbound variable

image

Fixing this by adding the following line to env vars on line 38 of the [lets_encrypt.yml](https://github.com/microsoft/AzureTRE/blob/1ffb09baf37f4599adfd65b4259fdda7564da408/.github/workflows/lets_encrypt.yml):

`AZURE_ENVIRONMENT= ${{ vars.AZURE_ENVIRONMENT }}`

Fixing the above then produces the next issue...

### 2. Fails on Azure login with tenant not found error

image

Looking more closely at the yaml, it looks like SUBCRIPTION_ID and TENANT_ID have their values mixed up:

https://github.com/microsoft/AzureTRE/blob/1ffb09baf37f4599adfd65b4259fdda7564da408/.github/workflows/lets_encrypt.yml#L41-L42

Fixing the above then produces the next issue...

### 3. Fails to initialise terraform backend

image

The error above is produced by the following lines:

https://github.com/microsoft/AzureTRE/blob/1ffb09baf37f4599adfd65b4259fdda7564da408/core/terraform/outputs.sh#L8-L15

Appears that the env vars and not making into the terraform initialize command... 

```
TF_VAR_mgmt_resource_group_name
TF_VAR_mgmt_storage_account_name
TF_VAR_terraform_state_container_name
```

Changing the following lines in letsencrypt.yaml from:

https://github.com/microsoft/AzureTRE/blob/1ffb09baf37f4599adfd65b4259fdda7564da408/.github/workflows/lets_encrypt.yml#L44-L47

to:

```
          TF_VAR_terraform_state_container_name: ${{ secrets.TERRAFORM_STATE_CONTAINER_NAME || 'tfstate' }}
          TF_VAR_mgmt_resource_group_name: ${{ secrets.MGMT_RESOURCE_GROUP_NAME }}
          TF_VAR_mgmt_storage_account_name: ${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}
```

fixes issue 3, and allows a certificate to be generated.

### PR DESCRIPTION
**Pull request by jonnyry**
# Resolves #3978

## What is being addressed

See details of issue, but in summary to fix the lets_encrypt.yml GitHub Action:

- missing variable:
  - AZURE_ENVIRONMENT 
- values of the following variables were the wrong way around:
  - ARM_SUBSCRIPTION_ID
  - ARM_TENANT_ID 
- following variables needed passing in TF_VAR_varname form:
  - TERRAFORM_STATE_CONTAINER_NAME
  - MGMT_RESOURCE_GROUP_NAME
  - MGMT_STORAGE_ACCOUNT_NAME

In addition, the following minor changes were made:

1. Add an environment selector to the workflow_dispatch, to allow users to run for different environments other than CICD.
2. Commented out the schedule dispatch - I can see its perpetually failing on microsoft/AzureTRE, suggest its left up to forkers to determine whether to run on a schedule and for which environment?  (though can re-introduce this if you think otherwise @marrobi @tim-allen-ck )

### CODE REVIEW

**Comment by jonnyry** [comment]
Hi @tim-allen-ck @marrobi would it be possible to review & merge this (small) PR?  thanks

**Comment by tim-allen-ck** [comment]
> Hi @tim-allen-ck @marrobi would it be possible to review & merge this (small) PR? thanks

can update the CHANGELOG ?

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by jonnyry** [comment]
@tim-allen-ck Added.

I also added an entry for the FIREWALL_SKU change, which I had missed.

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Pull request merged**
