### PR TITLE
Enhance DPI settings for Linux VM display

### LINKED ISSUE #4200: Linux VM VDI image is blurred.
When working on a Linux VM via Guacamole VDI the image is blurred. The DPI on the connection is too low and needs increasing. This needs to be acceptable on Windows too, maybe this can be user specified.

### PR DESCRIPTION
**Pull request by marrobi**
Increase the DPI settings for the Linux VM display to improve clarity and reduce blurriness. Documentation is updated to guide users on modifying the DPI settings.

Updated Gucamole server to 1.5.5.

Also enabled docker to run as a user without sudo.

Fixes #4200

### CODE REVIEW

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Review by LizaShak — APPROVED** [review]
LGTM

**Review by LizaShak — COMMENTED** [review]
What have increased the DPI? The Guacamole version upgrade?

**Comment by marrobi** [comment]
> What have increased the DPI? The Guacamole version upgrade?

This bit 'sudo -u "${VM_USER}" -i bash -c 'echo Xft.dpi: 192 >> ~/.Xresources' '

**Comment by marrobi** [comment]
/test-force-approve

Not tested

**Pull request merged**
