### PR TITLE
Add workflow default to RP_BUNDLE_VALUES

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

`RP_BUNDLE_VALUES` is an optional variable but its workflow default is an empty string (as is for any secret/var we use in the reusable workflow). That is invalid value in Terraform as the variable is defined as a map.

## How is this addressed

- Add `{}` as the workflow default for the param.

### CODE REVIEW

**Review by yuvalyaron — APPROVED** [review]

**Review by damoodamoo — APPROVED** [review]
sad face and many apologies from me :(

**Pull request merged**
