### PR TITLE
Resource processor - Re-instate az login and az acr login commands prior to porter explain command to fix microsoft/AzureTRE#3950

### LINKED ISSUE #3950: Resource processor fails to deploy first workspace on fresh TRE deployment
I deployed a new TRE from current main, and the first workspace I attempted to create fails (I've noticed this on fresh deploys a couple of times now) - the resource processor fails to deploy the workspace with the following message:

```
1) Main step for 88350ad0-8701-4dee-9698-834c9af1c6c8
88350ad0-8701-4dee-9698-834c9af1c6c8: Error message: parameter "tre_id" is required ; Command executed: porter install "88350ad0-8701-4dee-9698-834c9af1c6c8" --reference XXXXXXXX.azurecr.io/tre-workspace-nwsde-data-engineering:v1.6.1 --force --credential-set arm_auth --credential-set aad_auth
```

Creation of subsequent workspaces all succeed.

Here's the logs for the failed run:

image

I'm pretty sure the `get_porter_parameter_keys` function is failing the first time around, and specifically on the `porter explain` line:

https://github.com/microsoft/AzureTRE/blob/ddbbffe70fc6a8fe5d0b430afc4c18116f7ff993/resource_processor/resources/commands.py#L107

It looks like `az acr login` has not been called, and hence its causing the registry server to deny the request.  However porter install is still called despite not building the parameters, where `az acr login` *is* called - which is why subsequent runs work.

Looking at the commit history I can see the `az login` / `az acr login` were previously called before running `porter explain`:

image

Commit:

https://github.com/microsoft/AzureTRE/commit/c382f3daa041f337455ec47fef24eedad5ce55e6

Wondering if the `az login` & `az acr login` should have remained before calling `porter explain`?

### PR DESCRIPTION
**Pull request by jonnyry**
# Resolves #3950

## What is being addressed

Re-instate az login and az acr login commands prior to porter explain command to fix microsoft/AzureTRE#3950

### CODE REVIEW

**Review by marrobi — COMMENTED** [review]
LGTM

**Comment by jonnyry** [comment]
Hi @tim-allen-ck I've had a look at the test failures and I don't think its related to my change, but let me know if you think otherwise.

**Comment by tim-allen-ck** [comment]
> Hi @tim-allen-ck I've had a look at the test failures and I don't think its related to my change, but let me know if you think otherwise and I'll take another look.
> 
> 

Yeah nothing to do with your code changes, looks like an environment issue, I'm looking into it.

**Comment by tim-allen-ck** [comment]
@jonnyry can you update the commit with the latest main branch?

**Comment by jonnyry** [comment]
@tim-allen-ck updated to latest

**Pull request merged**
