### PR TITLE
Feature/GitHub actions update

### LINKED ISSUE #3847: Update GitHub Action Versions
## Description

As a TRE Developer
I want to use up do date actions
So that capabilities are kept.

Some of the actions might stop working soon as they are based on Node16 which is being removed by Github.

## Acceptance criteria

- [ ] All actions are updated to their latest version

(azure/login@v1.6.1 needs to be done)

### PR DESCRIPTION
**Pull request by tim-allen-ck**
# Resolves #3847

## What is being addressed

Some of the actions might stop working soon as they are based on Node16 which is being removed by Github.

## How is this addressed

- [x] All actions are updated to their latest version

- Describe the changes made, and if appropriate, why they are addressed this way
- Note any pending work (with links to the issues that will address them)
- Update documentation
- Update CHANGELOG.md if needed
- Increment template version if needed, for guidelines see [Authoring templates - versioning](https://microsoft.github.io/AzureTRE/tre-workspace-authors/authoring-workspace-templates/#versioning)

### CODE REVIEW

**Comment by marrobi** [comment]
Are there any other actions that need doing?

Issue says: `All actions are updated to their latest version`

The Azure one was a note as to not forget it, apologies if confusing.

**Comment by marrobi** [comment]
@tim-allen-ck suggest check the warnings at bottom of https://github.com/microsoft/AzureTRE/actions/runs/8540234100

**Comment by tim-allen-ck** [comment]
@marrobi ahh okay, no problem, think I was confused. I'll take another look.

**Comment by tim-allen-ck** [comment]
@marrobi just fyi technote-space/workflow-conclusion-action@v3 has been archived as of Nov 2023 and will not transition to node 20

**Comment by marrobi** [comment]
> @marrobi just fyi technote-space/workflow-conclusion-action@v3 has been archived as of Nov 2023 and will not transition to node 20

I'm not even sure its doing anything?

https://github.com/microsoft/AzureTRE/blob/086be3308dfeadb61c3a086082da6bd7612bc5a9/.github/workflows/deploy_tre_reusable.yml#L812-L830

As its the same level as the step below.

**Comment by tim-allen-ck** [comment]
> > @marrobi just fyi technote-space/workflow-conclusion-action@v3 has been archived as of Nov 2023 and will not transition to node 20
> 
> I'm not even sure its doing anything?
> 
> https://github.com/microsoft/AzureTRE/blob/086be3308dfeadb61c3a086082da6bd7612bc5a9/.github/workflows/deploy_tre_reusable.yml#L812-L830
> 
> As its the same level as the step below.

Looks like its used to notify the teams channel of a failed run

**Comment by marrobi** [comment]
> > > @marrobi just fyi technote-space/workflow-conclusion-action@v3 has been archived as of Nov 2023 and will not transition to node 20
> > 
> > 
> > I'm not even sure its doing anything?
> > https://github.com/microsoft/AzureTRE/blob/086be3308dfeadb61c3a086082da6bd7612bc5a9/.github/workflows/deploy_tre_reusable.yml#L812-L830
> > 
> > As its the same level as the step below.
> 
> Looks like its used to notify the teams channel of a failed run

That uses `sachinkundu/ms-teams-notification@1.4`

Not sure we use it either, and @sachinkundu has left MS, so might not be best to rely on that either. Can we delete the Teams notification piece for now.

**Comment by tim-allen-ck** [comment]
> > > > @marrobi just fyi technote-space/workflow-conclusion-action@v3 has been archived as of Nov 2023 and will not transition to node 20
> > > 
> > > 
> > > I'm not even sure its doing anything?
> > > https://github.com/microsoft/AzureTRE/blob/086be3308dfeadb61c3a086082da6bd7612bc5a9/.github/workflows/deploy_tre_reusable.yml#L812-L830
> > > 
> > > As its the same level as the step below.
> > 
> > 
> > Looks like its used to notify the teams channel of a failed run
> 
> That uses `sachinkundu/ms-teams-notification@1.4`
> 
> Not sure we use it either, and @sachinkundu has left MS, so might not be best to rely on that either. Can we delete the Teams notification piece for now.

Yep let remove, I'll add an issue to replace it with something else

**Review by wojciechcloudkubed — APPROVED** [review]

**Review by tamirkamara — APPROVED** [review]

**Pull request merged**
