### PR TITLE
Update packages for February Security Updates

### LINKED ISSUE #3865: February Security Updates
Update packages as per security alerts.

### PR DESCRIPTION
**Pull request by marrobi**
This pull request updates the packages as per the security alerts for February. Fixes #3865

### CODE REVIEW

**Comment by marrobi** [comment]
As long as these tests pass (which they did) https://github.com/microsoft/AzureTRE/pull/3866#issuecomment-1971518144, unless its not something covered by the tests we typically merge.

If a new feature then might deploy an instance and walk through the changes. 

Before do a release I typically deploy an environment and walk through everything.

**Review by tamirkamara — APPROVED** [review]

**Review by nasaldrops — APPROVED** [review]
LGTM

**Pull request merged**
