### PR TITLE
E2E tests: If shared service already exists, delete it first

### PR DESCRIPTION
**Pull request by tanya-borisova**
# PR for issue https://github.com/microsoft/AzureTRE/issues/1749

## What is being addressed

Make the main build more stable by checking in e2e tests that a shared service doesn't already exist before deploying it.
If it does, delete it first.

### CODE REVIEW

**Review by ross-p-smith — APPROVED** [review]

**Comment by tanya-borisova** [comment]
/test-force-approve

Successful PR run: https://github.com/microsoft/AzureTRE/actions/runs/2238486106

**Pull request merged**
