### PR TITLE
Tidy-up work for pr-comment-bot

### PR DESCRIPTION
**Pull request by stuartleeks**
- Format `if` conditions to reduce long lines
- Log command decision
- Remove permission debug job
- Fixup log message
- Remove unused PR repo values
- Only check first line of comment for command (allows adding other comment, e.g. notes/justification for test-force-approve)

Tidying up for #478 (not final, i.e. future PR will continue this work)

### CODE REVIEW

**Comment by ross-p-smith** [comment]
Have you done the linting?
Warning: orkspace/.github/workflows/pr_comment_bot.yml:1:1: [warning] missing document start "---" (document-start)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:19:81: [warning] line too long (81 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:37:81: [warning] line too long (121 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:38:81: [warning] line too long (124 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:39:81: [warning] line too long (88 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:41:81: [warning] line too long (115 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:50:81: [warning] line too long (115 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:51:81: [warning] line too long (105 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:65:81: [warning] line too long (117 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:77:81: [warning] line too long (109 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:104:81: [warning] line too long (413 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:118:81: [warning] line too long (103 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:121:81: [warning] line too long (94 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:123:81: [warning] line too long (86 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:124:81: [warning] line too long (120 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:135:81: [warning] line too long (86 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:175:81: [warning] line too long (86 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:215:81: [warning] line too long (81 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:222:81: [warning] line too long (92 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:252:81: [warning] line too long (90 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:254:81: [warning] line too long (93 > 80 characters) (line-length)
Warning: orkspace/.github/workflows/pr_comment_bot.yml:265:1: [warning] too many blank lines (1 > 0) (empty-lines)

**Comment by stuartleeks** [comment]
@ross-p-smith - I've fixed some lines. Still more to do.

How do I run the linter locally? (`make lint` didn't show anything for me)

**Comment by stuartleeks** [comment]
(also, I should have noted in the description that this isn't the final state of clean-up, but felt like a useful set to PR)

**Comment by ross-p-smith** [comment]
No easy way to run it locally as it runs a GH task. I also find I had to work from the bottom up as the line numbers would change 🤣

**Review by tanya-borisova — APPROVED** [review]

**Review by martinpeck — APPROVED** [review]
LGTM

**Pull request merged**
