### PR TITLE
Don't use Owner

### LINKED ISSUE #495: Can the scope of the VMSS MSI be reduced
**Description**
Currently this is subscription owner, can it be reduced to a custom role with lower privileges.

### PR DESCRIPTION
**Pull request by ross-p-smith**
## Fixes #495

The User assigned Identity does not need to be Owner, but rather "User Access Administrator".

### CODE REVIEW

**Comment by ross-p-smith** [comment]
/test-force-approve

(Previously succeeded)

**Review by damoodamoo — APPROVED** [review]

**Pull request merged**
