### PR TITLE
Fix - remove tags from kv

### PR DESCRIPTION
**Pull request by guybartal**
# PR for testing issue caused by merging #1888 

## What is being addressed

This PR is inteded to test if tagging KV causes recreation of secrets - [Deployment run](https://github.com/microsoft/AzureTRE/actions/runs/2412131796)

## How is this addressed

- remove tags from KV

### CODE REVIEW

**Review by eladiw — APPROVED** [review]

**Comment by guybartal** [comment]
I've closed this PR as #1947 fixed the issue of recovering the secrets

**Pull request closed without merging**
