### PR TITLE
Gitea/Guacamole should be able to access AAD_TENANT_ID

### LINKED ISSUE #1795: Guacamole and Gitea fail because Cannot access AAD_TENANT_ID variable
Since we changed AAD_TENANT_ID app setting in the api webapp to be referenced from keyvault, we now cannot access local. aad_tenant_id in both guacamole and gitea, resulting in both services crash.

### PR DESCRIPTION
**Pull request by ross-p-smith**
# Fixes #1795 

## What is being addressed

Gitea and Guacamole should be able to access the AAD_TENANT_ID when building workspace services

## How is this addressed

- Add the AAD_TENANT_ID into the ws KeyVault
- Gitea and Guacamole should read this value from Keyvault and not the core api app settings

### CODE REVIEW

**Review by marrobi — APPROVED** [review]
As long as it works, LGTM.

**Review by marrobi — CHANGES_REQUESTED** [review]
Are the deploy.sh files not still required?

**Comment by ross-p-smith** [comment]
> Are the deploy.sh files not still required?

They are used for local debugging and I have replaced them with a file called debug.sh which is more explicit what it is used for and added it to the dockerignore file

**Review by marrobi — APPROVED** [review]
LGTM. Thanks.

**Review by anatbal — APPROVED** [review]
LGTM

**Pull request merged**
