### PR TITLE
Apply missing lifecycle blocks to ignore tags

### LINKED ISSUE #3669: Resources are missing ignore_changes = [tags] leading to churn when tags are applied using policy
Resources are missing ignore_changes = [tags] leading to churn when tags are applied using policy.

`lifecycle { ignore_changes = [tags] }`

Needs adding to all resources that have tags applied by the Azure TRE.

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #3669

## How is this addressed

- Add missing lifecycle blocks to terraform resources to ignore tag changes

### CODE REVIEW

**Comment by marrobi** [comment]
Need to update version files and porter bundle versions

**Review by SvenAelterman — APPROVED** [review]
LGTM

**Comment by marrobi** [comment]
/test-force-approve

Passed: https://github.com/microsoft/AzureTRE/actions/runs/5831761555

**Comment by marrobi** [comment]
/test-force-approve

Passed: https://github.com/microsoft/AzureTRE/actions/runs/5854563391

**Pull request merged**
