### PR TITLE
Enable VS Code Extension Gallery to be proxied via Sonatype Nexus RM

### LINKED ISSUE #4187: Enable VS Code Extension Gallery to be proxied via Sonatype Nexus RM
Researchers need to be able to install VS Code extensions. 

The URLs start with `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/`

Content selectors on `path` can be used to restrict which publisher's extensions are able to be downloaded.

### PR DESCRIPTION
**Pull request by marrobi**
Fixes #4187

Add support for proxying VS Code Extension Gallery via Sonatype Nexus TM.

* **Documentation**: Update `docs/tre-templates/shared-services/nexus.md` to include instructions for configuring and using the VS Code extensions proxy.
* **Configuration Script**: Modify `templates/shared_services/sonatype-nexus-vm/scripts/configure_nexus_repos.sh` to add a new section for handling the VS Code extensions configuration.
* **Configuration File**: Add `templates/shared_services/sonatype-nexus-vm/scripts/nexus_repos_config/vscode_extensions_proxy_conf.json` with appropriate settings for proxying VS Code extensions.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/microsoft/AzureTRE/pull/4188?shareId=7abdcbad-9d22-4a5b-9474-f9c370adb457).

### CODE REVIEW

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Comment by marrobi** [comment]
/test-force-approve

Not tested.

**Review by LizaShak — APPROVED** [review]
LGTM

**Pull request merged**
