### PR TITLE
Primary bundles mirror Terraform providers

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

When we execute a bundle (like via install action) it needs outside communication to terraform domains to initialize itself which isn't ideal (see the issue for more info). 
This is part of #2353 which will be closed in a future PR.

## How is this addressed

- Call a terraform command to mirror providers locally at build time which will prevent any need for external communication at runtime
- Prepare the firewall for dropping the terraform domains more easily in the future
- Upgrade Terraform client to 1.2.6 and AzureRM to 3.16 in all the updated bundles
- In the base workspace, run vnet operations sequentially to prevent _AnotherOperation_ errors
- Minor (unrelated) changes in E2E

### CODE REVIEW

**Review by LizaShak — APPROVED** [review]

**Comment by tamirkamara** [comment]
/test-force-approve
Tests are currently broken due to unrelated change, but passed on a branch before this change was introduced.

**Pull request merged**
