### PR TITLE
Fix Guacamole firewall rule name

### PR DESCRIPTION
**Pull request by dusan-ilic-mhra**
Fix the name of a firewall rule in Guacamole as it wasn't correct.

### CODE REVIEW

**Review by tamirkamara — APPROVED** [review]
Thanks you @dusan-ilic-mhra for your contribution!

**Comment by dusan-ilic-mhra** [comment]
> Thanks you @dusan-ilic-mhra for your contribution!

You're welcome @tamirkamara

**Review by eladiw — APPROVED** [review]

**Pull request merged**
