### PR TITLE
Removes redundant malware scanning resources

### LINKED ISSUE #2441: Remove redundant malware scanning resources
## Description

Since Malware scanning was refactored there are a lot of unnecessary resource such as topics, role assignments etc,

### PR DESCRIPTION
**Pull request by anatbal**
# Fixes #2441 , #2417 

## What is being addressed

- Removes redundant malware scanning resources
- Change storage account from GRS to LRS

### CODE REVIEW

**Review by tamirkamara — APPROVED** [review]

**Comment by anatbal** [comment]
/test-force-approve
Tests had already ran

**Pull request merged**
