### PR TITLE
updated oauth2-proxy to version 7.3.0

### LINKED ISSUE #2732: Upgrade OAuth Proxy to 7.4.X
We current use oauth proxy 7.2.1, we need to upgrade to 7.3.0see

https://github.com/marrobi/AzureTRE/blob/4fa3e3dd5a08204fff1c171eabf3550713bbe80e/templates/workspace_services/guacamole/guacamole-server/docker/Dockerfile#L67

### PR DESCRIPTION
**Pull request by Lakshayainani**
# Resolves 
#2732

updated oauth2-proxy from 7.2.1 to 7.3.0

### CODE REVIEW

**Comment by tamirkamara** [comment]
Per the comment 7.3.1 didn't work out of the box in a previous attempt. Have you confirmed 7.3.0 does work?

**Comment by marrobi** [comment]
@tamirkamara Which comment are you referring to, agree this needs testing.

**Comment by tamirkamara** [comment]
> @tamirkamara Which comment are you referring to, agree this needs testing.

https://github.com/microsoft/AzureTRE/blob/main/templates/workspace_services/guacamole/guacamole-server/docker/Dockerfile#L66

Although it mentions 7.3.1 I remember I tried to upgrade and it didn't work.

**Review by tamirkamara — CHANGES_REQUESTED** [review]
As I mentioned in a previous comment upgrading the version isn't as easy as it doesn't work without other adjustments (which are unknown to me).

AuthZ fails with:
```
2022-10-19T19:16:56.026887890Z [2022/10/19 19:16:56] [oauthproxy.go:904] No valid authentication in request. Initiating login.
2022-10-19T19:16:57.162975034Z [2022/10/19 19:16:57] [oauthproxy.go:768] Error redeeming code during OAuth2 callback: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401": {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2022-10-19T19:16:57","request-id":"97b8d6e7-b65b-4b6d-a0a1-a84a8b9d63b7","client-request-id":"97b8d6e7-b65b-4b6d-a0a1-a84a8b9d63b7"}}}
```

**Comment by marrobi** [comment]
Looks like this: https://github.com/oauth2-proxy/oauth2-proxy/issues/1680

**Comment by tamirkamara** [comment]
Yes. It rings a bell...

**Comment by tamirkamara** [comment]
Per the discussion above this is more involved than just updating the version we use as the proxy has open issue regarding its Azure AuthNZ implementation in that version. Will close for now and revisit in the future.

**Pull request closed without merging**
