### PR TITLE
Switch to structured firewall logs

### PR DESCRIPTION
**Pull request by dusan-ilic-mhra**
# Resolves HASH_SIGN_FOLLOWED_BY_ISSUE_NUMBER

## What is being addressed

As Structured Logs are in general availability:
https://azure.microsoft.com/en-us/updates/general-availability-new-monitoring-and-logging-updates-in-azure-firewall/
we could switch to resource-specific tables

### CODE REVIEW

**Comment by marrobi** [comment]
Thanks, @dusan-ilic-mhra, can you take you take  look at https://techcommunity.microsoft.com/t5/azure-network-security-blog/azure-firewall-new-embedded-workbooks/ba-p/3999795 and check the appropriate log categories are enabled and the embedded workbook works correctly (check the various tabs). 

In the PR environment I see:

image

Might be it just needs more time. Once it does work we can remove this file - `/workspaces/marrobi-azure-tre/core/terraform/notebooks.tf`

**Comment by dusan-ilic-mhra** [comment]
@marrobi, I enabled these 3 log categories for now, as you can see from a commit in PR:

  firewall_diagnostic_categories_enabled = [
    "AZFWApplicationRule",
    "AZFWNetworkRule",
    "AZFWDnsProxy",
  ]

And, in my environment, I can see Azure Firewall Workbook works fine, for example:

image

DNAT actions are not showing as they are not enabled.

BR, 
Dusan

**Comment by marrobi** [comment]
@dusan-ilic-mhra thanks, they have appeared on the PR deployment, must have just needed some time.

Can you remove this workbook then - `/workspaces/marrobi-azure-tre/core/terraform/notebooks.tf` as don't believe its needed any more, and also update the changelog. Will try get it merged today. Thanks!

**Comment by dusan-ilic-mhra** [comment]
@marrobi, I removed ./core/terraform/notebooks.tf

Could you please update a changelog for me, as I'm not sure how to do it?

BR,
Dusan

**Comment by marrobi** [comment]
@dusan-ilic-mhra just add a line to this file - https://github.com/microsoft/AzureTRE/blob/main/CHANGELOG.md under enhancements as per the others.

**Comment by dusan-ilic-mhra** [comment]
@marrobi I've done it, but I needed to create a PR:
https://github.com/microsoft/AzureTRE/pull/3818
I haven't been able to commit directly.

**Comment by marrobi** [comment]
Not sure what you mean? Just add that change in your `dusan-ilic-mhra:dusanilic/switch-to-structured-firewall-logs branch` and push it?

**Comment by dusan-ilic-mhra** [comment]
@marrobi Done, thanks!

**Comment by marrobi** [comment]
@dusan-ilic-mhra  can you update the core version - `core/version.txt` - thanks.

**Comment by dusan-ilic-mhra** [comment]
@marrobi Done.

**Comment by marrobi** [comment]
@dusan-ilic-mhra you need to accept the CLA as per - https://github.com/microsoft/AzureTRE/pull/3816#issuecomment-1866257046 can you follow the instructions (paste the appropriate response into the comments). Thanks.

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by dusan-ilic-mhra** [comment]
@microsoft-github-policy-service agree company="MHRA"

**Comment by dusan-ilic-mhra** [comment]
> @dusan-ilic-mhra you need to accept the CLA as per - [#3816 (comment)](https://github.com/microsoft/AzureTRE/pull/3816#issuecomment-1866257046) can you follow the instructions (paste the appropriate response into the comments). Thanks.

@marrobi I accepted: 
https://github.com/microsoft/AzureTRE/pull/3816#issuecomment-1867668041

**Comment by marrobi** [comment]
/test-force-approve abc4adf

Passed above.

**Pull request merged**
