### PR TITLE
Update devcontainer/RP/API package versions: base Debian image, docker, azcli, YQ

### PR DESCRIPTION
**Pull request by jonnyry**
**1. Update devcontainer package versions:**

- base debian image from bullseye to bookworm
- Docker and its plugins
- Azure CLI
- YQ

**2. Update resource processor package versions:**

- base debian image from bullseye to bookworm
- Docker and its plugins

**3. Update API package version:**

- base debian image from bullseye to bookworm

This remediates a number of CVEs in container images.

### CODE REVIEW

**Review by tim-p-allen — APPROVED** [review]
LGTM haven't tested though

**Review by tamirkamara — APPROVED** [review]

**Pull request merged**
