### PR TITLE
Switch use of storage account keys by Terraform to use Azure AD authentication

### PR DESCRIPTION
**Pull request by marrobi**
Fixes issue #4103.

This pull request updates the Terraform code to switch from using storage account keys to using Azure AD authentication for operations on storage accounts. This change is necessary due to increasing policy restrictions on the use of storage account keys. The code changes include setting the `storage_use_azuread` flag to `true` in the provider block for the AzureRM provider. Additionally, the pull request includes updates to various modules and resources to enable Azure AD authentication. 

I've also removed old terraform migrations that delayed the testing, and a legacy cnab-state directory.

I've also included a helper script to increment all porter bundle versions in scenarios such as this.

Finally I fixed a bug with the health services bundle with the TF lock file that prevented it building. Again was needed for testing.

I've tested this myself, but would appreciate others giving it ago on a subscription with a policy banning the use of storage keys.

This does not fix issues of VM's using account keys to use storage and will have to be handled separately.

### CODE REVIEW

**Comment by marrobi** [comment]
@tamirkamara are you good to look at this? Also welcome ideas to fix the linting - I'm think the workflows will need updating to remove the tag check from the `./devops/` folder.

**Review by Danny-Cooke-CK — APPROVED** [review]
It looks good. Big change though. 64 files is a big one

**Comment by marrobi** [comment]
Two issues with this PR still:
- Linting of mgmt resources for TRE ID tag.
- The make command that runs `terraform show` fails.

**Review by LizaShak — APPROVED** [review]
I have tested it and it all worked for me. Thank you!

**Comment by LizaShak** [comment]
Hi @marrobi ,

The current test execution fails due to:
```
»»» 🤖 Creating resource group and storage account...
Location    Name
----------  -------------------
eastus      ***
WARNING: A storage account with the provided name *** is found. Will continue to update the existing account.
AccessTier    AllowBlobPublicAccess    AllowCrossTenantReplication    CreationTime                      EnableHttpsTrafficOnly    Kind       Location    MinimumTlsVersion    Name             PrimaryLocation    ProvisioningState    ResourceGroup        StatusOfPrimary
------------  -----------------------  -----------------------------  --------------------------------  ------------------------  ---------  ----------  -------------------  ---------------  -----------------  -------------------  -------------------  -----------------
Hot           False                    False                          2024-10-04T10:36:53.461064+00:00  True                      StorageV2  eastus      TLS1_0               ***  eastus             Succeeded            ***  available

»»» 🔑 Granting Storage Blob Data Contributor role to the current user...
ERROR: /me request is only valid with delegated authentication flow.
```
Looking at the code the responsible lines is:

```
USER_OBJECT_ID=$(az ad signed-in-user show --query id --output tsv)
```

I think that the sp used for the deployment needs Microsoft Graph permission of `User.Read`, who can help us with that? 

cc @tamirkamara

**Comment by marrobi** [comment]
@Danny-Cooke-CK @sconck can you help? Thanks.

**Comment by marrobi** [comment]
> Hi @marrobi ,
> 
> The current test execution fails due to:
> 
> ```
> »»» 🤖 Creating resource group and storage account...
> Location    Name
> ----------  -------------------
> eastus      ***
> WARNING: A storage account with the provided name *** is found. Will continue to update the existing account.
> AccessTier    AllowBlobPublicAccess    AllowCrossTenantReplication    CreationTime                      EnableHttpsTrafficOnly    Kind       Location    MinimumTlsVersion    Name             PrimaryLocation    ProvisioningState    ResourceGroup        StatusOfPrimary
> ------------  -----------------------  -----------------------------  --------------------------------  ------------------------  ---------  ----------  -------------------  ---------------  -----------------  -------------------  -------------------  -----------------
> Hot           False                    False                          2024-10-04T10:36:53.461064+00:00  True                      StorageV2  eastus      TLS1_0               ***  eastus             Succeeded            ***  available
> 
> »»» 🔑 Granting Storage Blob Data Contributor role to the current user...
> ERROR: /me request is only valid with delegated authentication flow.
> ```
> 
> Looking at the code the responsible line is:
> 
> ```
> USER_OBJECT_ID=$(az ad signed-in-user show --query id --output tsv)
> ```
> 
> I think that the sp used for the deployment needs Microsoft Graph permission of `User.Read`, who can help us with that?
> 
> cc @tamirkamara

@LizaShak thinking this needs a condition to get signed in user object if using logged in user as per the PR, or use the automation account - `ARM_CLIENT_ID`'s object ID if it is set. Do you agree?

**Comment by marrobi** [comment]
@yuvalyaron looks like these files needs the env vars so the MSI is used: `templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/delete_vm_extensions.sh`
`templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/delete_vm_extensions.sh`

**Pull request merged**
