### PR TITLE
Fix redacting secrets when sending messages to Resource Processor

### PR DESCRIPTION
**Pull request by tanya-borisova**
# PR for issue https://github.com/microsoft/AzureTRE/issues/2113 

## What is being addressed

In `save_and_deploy_resource`, we now manipulate with two resource objects: one is saved to Cosmos (with secrets redacted), another one is being sent to Resource Processor (with secrets intact). (see https://github.com/microsoft/AzureTRE/pull/2066). 
Thus, it is important that what is being sent to Resource Processor remains intact throughout, otherwise secret gets lost. 

In this PR, send the `resource` object provided to `send_resource_request_message` in order to preserve the un-redacted secrets that aren't saved in Cosmos DB.

## How is this addressed

- Pass through the resource object from the `save_and_deploy_resource` method
- Update tests so that the mock is set up on the downstream method, `send_deployment_message`

### CODE REVIEW

**Review by damoodamoo — APPROVED** [review]
As we've discussed - I think this is fine as a tactical solution, but has the limitations:
- will still fail if a resource is updated (either directly or as part of a pipeline)
- will only work in a pipeline if the primary resource is the first step

**Comment by tanya-borisova** [comment]
/test-force-approve

Some unrelated tests broke when I merged main last, but given there are successful runs (see above) I will merge this

**Pull request merged**
