### PR TITLE
JSON forms based schema for templates POST and GET

### PR DESCRIPTION
**Pull request by sachinkundu**
# PR for issue #420 #508 #509 

When registering a template a payload like 

```json
{
  "name": "my-tre-workspace-6",
  "version": "0.0.1",
  "current": "true",
  "json_schema": {
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://github.com/microsoft/AzureTRE/templates/workspaces/myworkspace/workspace.json",
    "type": "object",
    "title": "My Workspace Template Custom Parameters",
    "description": "These parameters are specific to my workspace template",
    "required": [
      "blah",
      "blah_2"
    ],
    "properties": {
      "blah": {
        "type": "string",
        "title": "VM size",
        "description": "Size of the VMs in my workspace",
        "default": "Standard_A1",
        "enum": [
          "Standard_A1",
          "Standard_A2",
          "Standard_A3"
        ]
      },
      "blah_2": {
        "type": "integer",
        "title": "Number of VMs",
        "description": "Number of virtual machines to be deployed in the workspace",
        "default": 0
      }
    }
  }
}
```
Notice the presence of **json_schema** sub document.

This will be stored as a **ResourceTemplate** in state store as

```json
{
    "id": "2b3f98a7-1152-4a24-8b9b-6513b8bb23e7",
    "name": "my-tre-workspace-6",
    "description": "These parameters are specific to my workspace template",
    "version": "0.0.1",
    "resourceType": "workspace",
    "current": true,
    "type": "object",
    "required": [
        "blah",
        "blah_2"
    ],
    "properties": {
        "blah": {
            "type": "string",
            "title": "VM size",
            "description": "Size of the VMs in my workspace",
            "default": "Standard_A1"
        },
        "blah_2": {
            "type": "integer",
            "title": "Number of VMs",
            "description": "Number of virtual machines to be deployed in the workspace",
            "default": 0
        }
    },
    "_rid": "q24aAPVBQEIHAAAAAAAAAA==",
    "_self": "dbs/q24aAA==/colls/q24aAPVBQEI=/docs/q24aAPVBQEIHAAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-83da-95af04e001d7\"",
    "_attachments": "attachments/",
    "_ts": 1627495286
}
```

When GET ``/api/workspace-templates/my-tre-workspace-6`` is done we will get an enriched response like

```json
{
  "id": "2b3f98a7-1152-4a24-8b9b-6513b8bb23e7",
  "name": "my-tre-workspace-6",
  "description": "These parameters are specific to my workspace template",
  "version": "0.0.1",
  "resourceType": "workspace",
  "current": true,
  "type": "object",
  "required": [
    "display_name",
    "description",
    "app_id",
    "blah",
    "blah_2"
  ],
  "properties": {
    "display_name": {
      "type": "string",
      "title": "Name for the workspace",
      "description": "The name of the workspace to be displayed to users",
      "default": null
    },
    "description": {
      "type": "string",
      "title": "Description of the workspace",
      "description": "Description of the workspace",
      "default": null
    },
    "address_space": {
      "type": "string",
      "title": "Address space",
      "description": "Network address space to be used by the workspace",
      "default": null
    },
    "app_id": {
      "type": "string",
      "title": "App Registration ID",
      "description": "AAD App registration of the workspace",
      "default": null
    },
    "blah": {
      "type": "string",
      "title": "VM size",
      "description": "Size of the VMs in my workspace",
      "default": "Standard_A1"
    },
    "blah_2": {
      "type": "integer",
      "title": "Number of VMs",
      "description": "Number of virtual machines to be deployed in the workspace",
      "default": 0
    }
  },
  "system_properties": {
    "tre_id": {
      "type": "string",
      "title": "",
      "description": "",
      "default": null
    },
    "workspace_id": {
      "type": "string",
      "title": "",
      "description": "",
      "default": null
    },
    "azure_location": {
      "type": "string",
      "title": "",
      "description": "",
      "default": null
    }
  }
}
```
Notice **required** **properties** and **system_properties** field. This is JSON schema compatible result and should be possible to generate auto UI from.

**NOTE** Validation tests have been removed as it makes little sense to fix tests which will be removed anyways since we are going to use JSON schema validation directly.

### CODE REVIEW

**Comment by marrobi** [comment]
Have you considered the pros/cons of having the schema as a subdocument in the registration payload vs the payload actually being the schema?

So maybe:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://github.com/microsoft/AzureTRE/templates/workspaces/myworkspace/workspace.json",
    "type": "object",
    "title": "my-tre-workspace-6",
    "version": "0.0.1",
    "current": "true",
    "description": "My workspace template",
    "required": [
      "blah",
      "blah_2"
    ],
    "properties": {
      "blah": {
        "type": "string",
        "title": "VM size",
        "description": "Size of the VMs in my workspace",
        "default": "Standard_A1",
        "enum": [
          "Standard_A1",
          "Standard_A2",
          "Standard_A3"
        ]
      },
      "blah_2": {
        "type": "integer",
        "title": "Number of VMs",
        "description": "Number of virtual machines to be deployed in the workspace",
        "default": 0
      }
    }
}
````

Not sure  which makes most sense.

**Comment by sachinkundu** [comment]
> Not sure which makes most sense.

Yes would have tried that but TBH could not figure out a method where $schema could be used as a key name in a dictionary. Probably some quoting stuff in python should enable it but was not straightforward. Also schema being a reserved keyword in pydantic had to use json_schema. I don't think the current request makes it too inconvenient either so did not want to spend more time on it. If you think it should be changed I can try to dig in

**Comment by marrobi** [comment]
@sachinkundu I'm happy with the JSON - but think this will break deployments as are currently relying on the porter parameters to know which fields to pass to porter.

So the parameters required by the bundle need to be either stored at registration time, or alternatively the runner could use `porter explain` to extract the required parameters and then provide the required values.

**Comment by marrobi** [comment]
I'd also take `system_properties` out of the JSON response. I don't see why we need to expose them as they are internal.

**Comment by sachinkundu** [comment]
> I'd also take `system_properties` out of the JSON response. I don't see why we need to expose them as they are internal.

I will remove this in the next patch. Just something extra and it was being reported before too.

**Review by marrobi — APPROVED** [review]
Happy from a "what it does" perspective, and understanding will need to be follow ups.

**Pull request merged**
