### PR TITLE
Error in tre_deploy, Set to use TF_VAR_ variables as purely a TF step

### PR DESCRIPTION
**Pull request by marrobi**
# PR for issue #209

## What is being addressed

The terraform deploy scripts should only use `TF_VAR_` variabless.

## How is this addressed

Changed the variable names to `TF_VAR_`

### CODE REVIEW

**Comment by limorl** [comment]
@marrobi The quickstart documentation should be updated, specifically this section, to match with the .env variables with the following var names. Also, the location of .env has changed:
image

**Comment by marrobi** [comment]
@limorl where is that screenshot from - can't see that on this branch.

**Comment by limorl** [comment]
> @limorl where is that screenshot from - can't see that on this branch.

quickstart.md

**Comment by marrobi** [comment]
@limorl when I look I see:
image

**Comment by limorl** [comment]
> @limorl when I look I see:
> image

Weird! I synced this branch. I'll force checking out this file.
Please ignore then

**Comment by limorl** [comment]
make-tre fails .
$TF_VAR_acr_name seems like it hasn't been set.

After setting it manually, there are still errors when running terraform init 
image

**Comment by marrobi** [comment]
@limorl it will fail, as the make file creates the backend configuration. Can you paste the output of `make tre_deploy` ?

**Comment by limorl** [comment]
I opened another bug when running on a clean env:
https://github.com/microsoft/AzureTRE/issues/280

**Review by christoferlof — APPROVED** [review]
Everything that was in scope for this PR is working fine when testing it. However, there is some unnecessary confusion introduced by mentioning environment variables which are not required for the quickstart scenario. Will create separate issues to address.

**Pull request merged**
