### PR TITLE
Add dependency on firewall deployment to rule collection

### LINKED ISSUE #3671: In E2E tests Firewall doesn't deploy as Subnet not ready
>Cannot proceed with operation because resource /subscriptions/bb0916b2-1642-4efb-897d-a41ecc9fd132/resourceGroups/rg-treaf207fb6/providers/Microsoft.Network/virtualNetworks/vnet-treaf207fb6/subnets/AzureFirewallSubnet used by resource /subscriptions/bb0916b2-1642-4efb-897d-a41ecc9fd132/resourceGroups/rg-treaf207fb6/providers/Microsoft.Network/azureFirewalls/fw-treaf207fb6 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #3671

Add dependancy on rule collection to Firewall. It is deploying before the Firewall has completed and is in a Succeeded state causing the issue referenced.

- [x] Update CHANGELOG.md if needed

### CODE REVIEW

**Review by SvenAelterman — APPROVED** [review]
LGTM

**Comment by marrobi** [comment]
/test-force-approve

Passed: https://github.com/microsoft/AzureTRE/actions/runs/5867301767

**Comment by marrobi** [comment]
/test-force-approve

Passed: https://github.com/microsoft/AzureTRE/actions/runs/5867301767

**Pull request merged**
