### PR TITLE
Ensure az output is in expected format

### LINKED ISSUE #1451: Deployment fails with "Resource group 'rg-tresl' could not be found" on `make all`
**Describe the bug**
When running `make all` for a fresh deployment, the following error is reported and the deployment fails:

```
Resource group 'rg-tresl' could not be found
```

**Steps to reproduce**

1. Delete any resource groups from previous Azure TRE deployments
1. Delete `.terraform` folders locally
1. Run `make all`

### PR DESCRIPTION
**Pull request by stuartleeks**
Fixes #1451

### CODE REVIEW

**Review by martinpeck — APPROVED** [review]
LGTM

**Review by ross-p-smith — COMMENTED** [review]
This cant be the only place with this. Have you fixed the others or just doing them as and when you find them?

**Comment by stuartleeks** [comment]
> This cant be the only place with this. Have you fixed the others or just doing them as and when you find them?

Currently as-and-when

**Pull request merged**
