### PR TITLE
API Swagger fix: switch lstrip with replace

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

Sometimes a scope_id would get malformed when swagger uses it to get a token from AAD.
For example api://a173fe93... is being used as api://173fe93... notice the missing a in the beginning. 
The cause is us using a python lstrip which strips all char occurrences.

## How is this addressed

- Switch lstrip with replace

### CODE REVIEW

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by ross-p-smith** [comment]
Great spot - that was introduced during Code Review!

**Comment by tanya-borisova** [comment]
Sorry that was my fault :(

**Pull request merged**
