### PR TITLE
AML bundle fails due to missing tags

### LINKED ISSUE #2197: AML bundle fails due to missing tre_workspace_service_tags variable
When deploying the AzureML workspace service get:

```
No value for required variable[0m [31m│[0m [0m [31m│[0m [0m[0m on variables.tf line 12: [31m│[0m [0m 12: [4mvariable "tre_workspace_service_tags"[0m {}[0m [31m│[0m [0m [31m│[0m [0mThe root module input variable "tre_workspace_service_tags" is not set, and [31m│[0m [0mhas no default value.
```

### PR DESCRIPTION
**Pull request by pedro-pelegrin-nttdata**
Fixes #2197

## What is being addressed

AML bundle fails due to missing tre_workspace_service_tags variable.

## How is this addressed

Fixing tre_workspace_id variable workspace_id, tre_workspace_service_id variable
tre_resource_id

### CODE REVIEW

**Review by guybartal — DISMISSED** [review]
- is ```tre_workspace_service_tags``` variable inside ```templates/workspace_services/azureml/terraform/variables.tf``` really need?

- the variable named ```tre_workspace_tags``` inside ```templates/workspace_services/azureml/terraform/acr/variables.tf``` suggest this is a workspace and not workspace service

- acr inside ```templates/workspace_services/azureml/terraform/acr/main.tf``` missed tagging, can you please tag it with workspace service tags?

**Comment by marrobi** [comment]
Hi @pedro-pelegrin-nttdata thanks for looking at this. Can you upgrade the porter bundle version in porter.yaml please. I have pulled your code (update the version) and successfully deployed AML. Thanks.

**Pull request merged**
