### PR TITLE
Disable terraform's checkpoint procedure

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

After confirming the fix to disable Terraform's checkpoint mechanisem works well in the TRE, this PR expands it to all bundles.
It also removes the providers folder created by the init command as those are anyway mirrored to a separate folder.

### CODE REVIEW

**Review by stuartleeks — APPROVED** [review]
LGTM if tests are passing - thanks @tamirkamara 😄

**Comment by tamirkamara** [comment]
/test-force-approve
tests have passed but ui upload failed for a weird reason so decided to merge anyway

**Pull request merged**
