### PR TITLE
Amend conda configuration in Nexus

### PR DESCRIPTION
**Pull request by JaimieWi**
# Resolves: Conda support in Nexus
No issue number. 
## What is being addressed

The configuration of conda within the VMs and Nexus did not allow for certain packages to be installed. This was due to the `location of the remote repository being proxied` pointing to `https://conda.anaconda.org/conda-forge`, and so a package like pytorch or torchvision couldn't be installed as it comes from `https://conda.anaconda.org/pytorch`. The `main` also needed to be removed from Nexus and added to the .condarc file.

**Nexus before**
image
image

## To reproduce the error
1. run `conda create --name test python=3.9`
2. run `conda activate test`
3. run `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`
The below error will occur:
image
image

## How is this addressed
- The conda configuration in Nexus needed to change to allow access to the entire `https://conda.anaconda.org/` repository
- The configuration of conda within the VMs (the contents of .condarc) needed to be updated accordingly.
  - I have called the two repositories `conda` and `conda2`.

**Nexus after**
image
image

**Contents of .condarc**
image

**Result**
image
image

### CODE REVIEW

**Comment by marrobi** [comment]
@JaimieWi thanks very much for the PR, so there are two repos needed?
```
https://repo.anaconda.com/pkgs/main
https://conda.anaconda.org/
```
Can the names relate to these URIs?

**Comment by JaimieWi** [comment]
> @JaimieWi thanks very much for the PR, so there are two repos needed?
> 
> ```
> https://repo.anaconda.com/pkgs/main
> https://conda.anaconda.org/
> ```
> 
> Can the names relate to these URIs?

Yes the two are needed I believe, there are different packages in each. I was thinking to do that but wasn't sure what was best. I could change them to `repo_anaconda` and `conda` ?

Just to add: The repo_anaconda one has to be as `https://repo.anaconda.com/pkgs/`.

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by marrobi** [comment]
/test-force-approve a3f654e

Not covered by e2e tests.

**Comment by marrobi** [comment]
/test-force-approve a3f654e

Not covered by e2e tests.

**Pull request merged**
