### PR TITLE
Add prevent destroy to cosmos and firewall

### PR DESCRIPTION
**Pull request by marrobi**
Issue #916

Add prevent destroy to firewall and cosmos resources to ensure are not accidently deleted by terraform.

### CODE REVIEW

**Comment by Lybecker** [comment]
Will the `make tre-destroy` still work?

**Comment by marrobi** [comment]
@Lybecker good point. Could wrap them with a condition of based on an ENV var maybe? We need to block them being destroyed accidentally somehow. 

Could use Azure locks, but a destroy could destroy the lock too.

**Comment by marrobi** [comment]
Can't do conditions - https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#literal-values-only so you are correct would block a destroy. Should look at Azure management locks instead.

**Comment by Lybecker** [comment]
Can the make tre-destroy modify the prevent_destroy before the actual TF destroy?

**Comment by marrobi** [comment]
Nope, I'll give this another go with azure locks.

**Pull request closed without merging**
