### PR TITLE
Simplify teams notification

### PR DESCRIPTION
**Pull request by tamirkamara**
## What is being addressed

Send MSTeams notification when the deploy workflow fails.

## How is this addressed

- All success notifications are removed
- A single notification step is run at the end of the workflow instead after/in individual steps
- The notification is generic - i.e. "failure..."

### CODE REVIEW

**Review by ross-p-smith — APPROVED** [review]

**Review by stuartleeks — APPROVED** [review]
LGTM

**Review by martinpeck — APPROVED** [review]
LGTM :)

**Comment by tamirkamara** [comment]
forced approved based on this run: https://github.com/microsoft/AzureTRE/actions/runs/1929439315

**Pull request merged**
