### PR TITLE
Deprecate and remove ML Flow and InnerEye bundles

### PR DESCRIPTION
**Pull request by marrobi**
Remove the ML Flow and InnerEye workspace services due to their deprecation and lack of maintenance. Users can retrieve previous versions if needed. This change addresses issue #4127.

### CODE REVIEW

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Review by Danny-Cooke-CK — APPROVED** [review]

**Comment by tim-allen-ck** [comment]
tests fails due mlflow being non-existent so forcing them through

**Pull request merged**
