### PR TITLE
Fix CycleCloud and SLURM deployment issues

### LINKED ISSUE #2406: Required ports missing for services to function.
A number of recent and future workspace services, such as, CycleCloud and Cromwell require additional ports opening. These were missed of the PR.

Port 22 is required from the Resource Processor subnet to the workspace to allow files to be provisioned onto workspace VMs

Ports 111 (TCP and UDP) and 2049 (TCP and UDP) are needed within the workspace services subnet to allow NFS communication.

### PR DESCRIPTION
**Pull request by marrobi**
Fixes #2406, #3933, #4026, #4021

Update cloudinit for changes in VM configuration
Add firewall rules from shared service subnet to GitHub so resources can be downloaded.

### CODE REVIEW

**Review by tim-allen-ck — APPROVED** [review]
LGTM

**Review by Danny-Cooke-CK — APPROVED** [review]
approved

**Comment by tim-allen-ck** [comment]
> Hi team, thank you for your efforts! It seems this merge request is still open. Could you please check and approve the merge if it's okay? After merging, will the changes be applied immediately when running the `$ make all` command, or should we wait for the version 0.20 release? @marrobi @tim-allen-ck

Hi @BiologyGeek merging it now. 
Yes a `make all` will be easiest, then either create a new Cyclecloud resource or you'll have to upgrade your current one.

**Pull request merged**
