### PR TITLE
Fixing Bug 280 + Bug 297 + documentation typos

### PR DESCRIPTION
**Pull request by limorl**
# PR for issue #280 #297

## What is being addressed
Bug 280 - az and docker commands in the Makefile scripts fail on permissions
Bug 297 - set_contributor_sp_secrets.sh fails since the varialbes weren't loaded properly. 

Describe the current behavior you are modifying

## How is this addressed

- Bug 280:  When running from dev container (on Mac), az and sudo commands require running in sudo mode.
- Bug 297 - load_env was ran prior to this script to load the correct variables

### CODE REVIEW

**Comment by limorl** [comment]
submitted prematurely

**Comment by sachinkundu** [comment]
Instead of sudo for docker everywhere have you tried adding $USER to the docker group?

**Comment by limorl** [comment]
> Instead of sudo for docker everywhere have you tried adding $USER to the docker group?

Yes I have tried it Sachin and it didn;t work well with dev containers. Hence I added inline.

**Review by TessFerrandez — APPROVED** [review]

**Comment by limorl** [comment]
> > Instead of sudo for docker everywhere have you tried adding $USER to the docker group?
> 
> Yes I have tried it Sachin and it didn;t work well with dev containers. Hence I added inline.

To be more accurate, adding user is done differently on MAC and wasn't a very good option.
I did follow these guidelines but it didn;t work for me: https://code.visualstudio.com/docs/remote/containers

**Pull request merged**
